federated_learning:
  num_clients: 3
  num_rounds: 100  # Reduced for quick testing
  local_epochs: 2
  batch_size: 32
  learning_rate: 0.01
  aggregation: "FedAvg"
  device: "cpu"  # Using CPU for compatibility

model:
  name: "SimpleCNN"
  input_channels: 3
  num_classes: 7  # PACS has 7 classes
  small_dim: 64   # Dimension of small embedding
  mapper_hidden_dim: 256   # Hidden dimension of mapper
  clip_dim: 512   # CLIP embedding dimension

data:
  domains: ["photo", "art_painting", "cartoon", "sketch"]
  test_domain: "photo"  # Domain to use for testing
  img_size: 64
  data_path: "./data/PACS"

logging:
  save_model: True
  save_path: "./checkpoints"
  log_interval: 1  # Log every round

# CLIP alignment settings
lambda_align: 0.1
use_dp_noise: False
dp_noise_std: 0.01
plot_each_round: True 