federated_learning:
  num_clients: 4
  num_rounds: 100  # Reduced from 5 to 2 for even quicker testing
  local_epochs: 2
  batch_size: 64
  learning_rate: 0.01
  aggregation: "FedAvg"
  device: "cuda"  # or "cpu"

model:
  name: "SimpleCNN"
  input_channels: 3
  num_classes: 7  # PACS has 7 classes

data:
  domains: ["photo", "art_painting", "cartoon", "sketch"]
  test_domain: "photo"  # Domain to use for testing
  img_size: 64
  data_path: "./data/PACS"

logging:
  save_model: True
  save_path: "./checkpoints"
  log_interval: 1  # Log every round 